.github/issue_template.md
.github/pull_request_template.md

- Para uma maior organização, foram criados os templates de issues e de pull requests que devem ser seguidos pelos membros da equipe.
- #1
* Adicionado template de issues e de pull requests

Adicionando template de issues e pull requests

---

.github/workflows/ci.yml
mkdocs.yml

- Implementação do mkdocs para documentação e deploy automático.
-  #2
* Implementação do mkdocs
* Deploy automático (github actions)

#2 Adicionando mkdocs e deploy automático

---

docs/apresentacoes/p1.md
mkdocs.yml

- Adição do documento de apresentações e do primeiro ponto de controle.
- #6 
* Adição documento de apresentação
* Documento contendo a primeira apresentação

#6 Adição do primeiro ponto de controle

---

docs/index.md
docs/planejamento/index.md
docs/pre_rastreabilidade/rich_picture.md

- Correções de legendas e referências de todos os documentos do projeto
- #16 
* Correção do index
* Correção do planejamento
* Correção da pré rastreabilidade

#16 Correções de legendas e referências

---

docs/atas/ata05_08.md
docs/atas/ata27_07.md
mkdocs.yml

- Documentação das atas relativas as reuniões já realizadas
- #19
* Documentação da ata dia 27/07
* Documentação da ata dia 05/08
* Adição das rotas no mkdocs

Adição dos documentos contendo as atas

---

docs/index.md

- Foi adicionado ao arquivo principal do mkdocs a justificativa de escolha do aplicativo Ingresso.com pelo grupo.
-  #24 
* Edição do documento index

#24 Justificativa de Escolha do App

---

docs/elicitacao/analiseProtocolo.md
mkdocs.yml

Foi feita a análise de protocolo baseando-se nas atitudes de um usuários externo ao grupo que já utilizou o app uma vez, será verbalizada suas ações por meio de uma gravação de tela e aúdio referente ao uso do aplicativo.
- #27 
* Feita a análise de protocolo
* Levantado os requisitos baseados na análise de protocolo

#27 Documento de análise de protocolo

---

docs/elicitacao/introspeccao.md
mkdocs.yml

Trabalhando nas introspecções.
- Adição da introdução
- Adição das introspecções
- Adição das referencias
- #25
* Adição do documento de introspeção

#25 Elicitação - Introspecção

---

docs/elicitacao/brainstorming.md
mkdocs.yml

Foi elaborado o documento de brainstorming através de uma reunião via discord com os integrantes: Rafael, Vitor Lamego e Thiago. Foram abordadas algumas perguntas para promover uma dinâmica bacana na elicitação e após essas perguntas foram elicitados os requisitos em conjunto pela equipe.
- #20 
* Feito um brainstorming através de perguntas chaves.
* Elicitado os requisitos baseados em algumas respostas e discussões da equipe

#20 Documento de brainstorming

---

docs/apresentacoes/p1.md
docs/apresentacoes/p2.md
mkdocs.yml

- Adição do documento contendo apresentação 2 do grupo
- #47 
* Criação do documento
* Adição do vídeo
* Modificação mkdocs

#47 Adição do ponto de controle 2

---

docs/planejamento/index.md

- Foi melhorado o cronograma, tornando o mais detalhado
- #53 
* Detalhamento do cronograma

#53 Melhoria do cronograma

---

docs/apresentacoes/p1.md
docs/apresentacoes/p2.md
docs/apresentacoes/p3.md
docs/planejamento/index.md
mkdocs.yml

- Adição do vídeo e slides do 3 ponto de controle e melhoria cronograma
- #61 
* Adição vídeo
* Adição slides
* Melhoria cronograma

#61 Ponto de controle 3

---

docs/apresentacoes/p4.md
docs/planejamento/index.md
mkdocs.yml

- Adição do vídeo e slides do 4 ponto de controle e melhoria cronograma
- #72 
* Adição vídeo
* Adição slides
* Melhoria cronograma

#72 Ponto de controle 4

---

docs/verificacao/istar.md
mkdocs.yml

- Criação do documento de verificação do artefato iStar
- #74 
* Criação do documento de verificação
* Modificação da rota do mkdocs

#74 Verificação iStar

---

docs/verificacao/nfr.md
mkdocs.yml

- Criação do documento de verificação do NFR Framework
- #86  
* Verificação dos NFR por Inspeção (Checklist)
* Conclusão referente a verificação

#86 Verificação NFR Framework

---

docs/verificacao/istar.md
docs/verificacao/lexicos.md
mkdocs.yml

- Criação do documento de verificação dos Léxicos e adição da conclusão
- #79 
* Verificação dos Léxicos por Inspeção (Checklist)
* Conclusão referente a verificação
* Correção de erros ortográficos que estavam presentes no projeto anteriormente

#79 Verificação Léxicos

---

docs/verificacao/cenarios.md
mkdocs.yml

Neste pull request foi criado um documento para verificação dos cenários construídos no projeto, técnica de modelagem utilizada anteriormente. Assim como as conclusões e os resultados da introspecção feita a partir do documento da Wiki.
- Descreva aqui as alterações a serem implementadas no projeto.
- #83 
* Criação do documento
* Definição do checklist
* Construção das tabelas de análise
* Conclusão com resultados.

#83 Verificação Cenários

---

docs/modelagem/lexicos.md
docs/validacao/viewpoint.md
mkdocs.yml

- Documento contendo a validação pela técnica de viewpoint
- #75 
* Adição do documento de validação
* Criação da rota no mkdocs
* Lexicos linkados

#75 Validação Viewpoint

---

docs/apresentacoes/p5.md
docs/planejamento/index.md
mkdocs.yml

- Adição do vídeo e slides do 5 ponto de controle e melhoria cronograma
- #92 
* Adição vídeo
* Adição slides
* Melhoria cronograma

#92 Ponto de controle 5

---

docs/validacao/validacao_informal.md
mkdocs.yml

- Realização da Validação Informal do projeto.
- #84 
* Contato com a empresa
* Contato com funcionários
* Criação do documento
* Possível atualização do documento após recebimento de resposta

#84 Validação Informal
